### PR TITLE
Add a parameter for an external hostname field

### PR DESCRIPTION
**Pull request by NickHu**
I haven't actually written anything here, I just rebased @jmahowald's pr #888 onto `master`, but it seems to work fine. I'm willing to pick it up if you think there's anything that needs to be done before this can be merged though.

Here's my use case:

Registry configured at `http://registry.my.host:5000`
Portus configured at `http://registry.my.host:3000/portus`
Apache SSL proxying `https://registry.my.host/portus -> http://registry.my.host:3000/portus` and `https://registry.my.host/v2 -> http://registry.my.host:5000/v2`
So in Portus, I have configured the registry as:
screenshot from 2016-08-01 10-31-32

### CODE REVIEW

**Comment by NickHu** [comment]
The only issue that I have is I can't seem to be able to delete images, despite having delete enabled in both the registry and Portus.

Here are my steps:

* Create a new user for myself to use the registry in Portus, `nickhu`
* Login: `docker login -u nickhu -p password registry.my.host` (successful)
* Push a test image: `docker push registry.my.host/nickhu/hello-world` (successful)

Then when I go to delete the tag in the Portus UI, I get a notification saying `Tag could not be removed`.

Here are the relevant logs:

```
portus_1    | Started DELETE "/portus//tags/1" for 163.1.125.245 at 2016-08-01 09:37:06 +0000
portus_1    | Processing by TagsController#destroy as HTML
portus_1    |   Parameters: {"authenticity_token"=>"gO7twoL7OjZyoCzGNcYCnLBFgNCbhsY6QDhdWbX3LQuJDm+/Mric7S2QS+zkv4ZdIFgKn2Hv0FaZvBEQKLHhLA==", "id"=>"1"}
portus_1    |   User Load (0.5ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1
portus_1    |    (0.3ms)  SELECT COUNT(*) FROM `registries`
portus_1    |   Tag Load (0.8ms)  SELECT  `tags`.* FROM `tags` WHERE `tags`.`id` = 1 LIMIT 1
portus_1    |   Repository Load (0.3ms)  SELECT  `repositories`.* FROM `repositories` WHERE `repositories`.`id` = 1 LIMIT 1
portus_1    |   SQL (8.9ms)  UPDATE `tags` SET `tags`.`marked` = 1 WHERE `tags`.`digest` = 'sha256:0256e8a36e2070f7bf2d0b0763dbabdd67798512411de4cdcf9431a1feb60fd9'
portus_1    |   Registry Load (0.4ms)  SELECT  `registries`.* FROM `registries`  ORDER BY `registries`.`id` ASC LIMIT 1
portus_1    |   Namespace Load (0.4ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 3 LIMIT 1
registry_1  | time="2016-08-01T09:37:06.971274108Z" level=warning msg="error authorizing context: authorization token required" go.version=go1.6.2 http.request.host="registry.my.host:5000" http.request.id=bbf07e71-aa9e-4d07-950c-735e09a0e083 http.request.method=DELETE http.request.remoteaddr="172.17.0.1:48152" http.request.uri="/v2/nickhu/hello-world/manifests/sha256:0256e8a36e2070f7bf2d0b0763dbabdd67798512411de4cdcf9431a1feb60fd9" http.request.useragent=Ruby instance.id=ced69485-7553-42cb-a5be-89a2d34f7795 service=registry vars.name="nickhu/hello-world" vars.reference="sha256:0256e8a36e2070f7bf2d0b0763dbabdd67798512411de4cdcf9431a1feb60fd9" version=v2.4.1
registry_1  | 172.17.0.1 - - [01/Aug/2016:09:37:06 +0000] "DELETE /v2/nickhu/hello-world/manifests/sha256:0256e8a36e2070f7bf2d0b0763dbabdd67798512411de4cdcf9431a1feb60fd9 HTTP/1.1" 401 147 "" "Ruby"
portus_1    | Could not delete tag on the registry: SSL_connect returned=1 errno=0 state=error: certificate verify failed
portus_1    | Redirected to https://registry.my.host/portus/repositories/1
portus_1    | Completed 302 Found in 63ms (ActiveRecord: 11.6ms)
portus_1    | Started GET "/portus//repositories/1" for 163.1.125.245 at 2016-08-01 09:37:07 +0000
portus_1    | Processing by RepositoriesController#show as HTML
portus_1    |   Parameters: {"id"=>"1"}
portus_1    |   User Load (1.0ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 1  ORDER BY `users`.`id` ASC LIMIT 1
portus_1    |    (0.4ms)  SELECT COUNT(*) FROM `registries`
portus_1    |   Repository Load (0.4ms)  SELECT  `repositories`.* FROM `repositories` WHERE `repositories`.`id` = 1 LIMIT 1
portus_1    |   Tag Load (1.0ms)  SELECT `tags`.* FROM `tags` WHERE `tags`.`repository_id` = 1
portus_1    |   Star Exists (0.4ms)  SELECT  1 AS one FROM `stars` WHERE `stars`.`repository_id` = 1 AND `stars`.`user_id` = 1 LIMIT 1
portus_1    |   CACHE (0.0ms)  SELECT  1 AS one FROM `stars` WHERE `stars`.`repository_id` = 1 AND `stars`.`user_id` = 1 LIMIT 1  [["repository_id", 1]]
portus_1    |    (0.4ms)  SELECT COUNT(*) FROM `stars` WHERE `stars`.`repository_id` = 1
portus_1    |   Namespace Load (0.4ms)  SELECT  `namespaces`.* FROM `namespaces` WHERE `namespaces`.`id` = 3 LIMIT 1
portus_1    |   Team Load (0.3ms)  SELECT  `teams`.* FROM `teams` WHERE `teams`.`id` = 3 LIMIT 1
portus_1    |   User Exists (0.3ms)  SELECT  1 AS one FROM `users` INNER JOIN `team_users` ON `users`.`id` = `team_users`.`user_id` WHERE `team_users`.`team_id` = 3 AND `team_users`.`role` = 2 AND `users`.`id` = 1 LIMIT 1
portus_1    |   User Exists (0.4ms)  SELECT  1 AS one FROM `users` INNER JOIN `team_users` ON `users`.`id` = `team_users`.`user_id` WHERE `team_users`.`team_id` = 3 AND `team_users`.`role` = 1 AND `users`.`id` = 1 LIMIT 1
portus_1    |   User Exists (0.5ms)  SELECT  1 AS one FROM `users` INNER JOIN `team_users` ON `users`.`id` = `team_users`.`user_id` WHERE `team_users`.`team_id` = 3 AND `team_users`.`role` = 0 AND `users`.`id` = 1 LIMIT 1
portus_1    |   User Load (0.4ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 2 LIMIT 1
portus_1    |    (0.3ms)  SELECT COUNT(*) FROM `comments` WHERE `comments`.`repository_id` = 1
portus_1    |   CACHE (0.0ms)  SELECT COUNT(*) FROM `comments` WHERE `comments`.`repository_id` = 1  [["repository_id", 1]]
portus_1    |   CACHE (0.0ms)  SELECT COUNT(*) FROM `comments` WHERE `comments`.`repository_id` = 1  [["repository_id", 1]]
portus_1    |   Rendered repositories/show.html.slim within layouts/application (74.7ms)
portus_1    |   Rendered shared/_header.html.slim (2.7ms)
portus_1    |   Rendered shared/_aside.html.slim (1.3ms)
portus_1    |   Rendered shared/_search.html.slim (1.4ms)
portus_1    |   CACHE (0.1ms)  SELECT COUNT(*) FROM `registries`
portus_1    |   Rendered shared/_notification.html.slim (0.2ms)
portus_1    |   Rendered shared/_notification.html.slim (0.1ms)
portus_1    |   Rendered shared/_notifications.html.slim (6.3ms)
portus_1    | Completed 200 OK in 113ms (Views: 92.1ms | ActiveRecord: 6.4ms)
portus_1    | Started GET "/portus//assets/layout/portus-logo-dashboard-52774571adac55477c70b8a46ffe46ec.png" for 163.1.125.245 at 2016-08-01 09:37:07 +0000
portus_1    | Started GET "/portus//assets/layout/bg-fd012f5f03eb0ffcff1638fff257962e.png" for 163.1.125.245 at 2016-08-01 09:37:07 +0000
portus_1    | Started GET "/portus//assets/fontawesome-webfont-e953816ef3a22ec5b72389b60e3e3039.woff2?v=4.4.0" for 163.1.125.245 at 2016-08-01 09:37:07 +0000
portus_1    | Started GET "/portus//assets/raleway-1e13ee0db82aba7cb678ca43b21b21e2.woff2" for 163.1.125.245 at 2016-08-01 09:37:08 +0000
portus_1    | Started GET "/portus//assets/raleway-bold-f924615cbcec51904b6d0a9308575cba.woff2" for 163.1.125.245 at 2016-08-01 09:37:08 +0000
```

Portus seems to be failing at a SSL verify between communicating with the registry, but Apache (which is handling all SSL) generates no errors for this event. In fact, I'm not really sure why internally Portus seems to be trying to communicate with the registry via SSL.

**Comment by mssola** [comment]
As I said in the PR you are mentioning, I have nothing against this change. Your issues with deleting might be due to the registry client that we have implemented in `lib/portus`. Take a look at it and update it :wink:

**Comment by jmahowald** [comment]
Sorry about dropping the ball.  I had another project that it looks like Portus is the best solution for.  I'll rebase off of this one and start contributing.  If my memory is serving me I was trying to decide the best way to write a spec case for it and was either having some difficulties or got distracted.  Squirrel!

**Comment by NickHu** [comment]
With regards to my issue, it seems as though the registry client is not respecting SSL certificates (and also ignoring `/etc/ssl/cert.pem` (`ruby -ropenssl -e 'puts OpenSSL::X509::DEFAULT_CERT_FILE'`) and the `SSL_CERT_FILE` environment variable).

I can get the delete to succeed by editing `get_response_token` in `lib/portus/http_helpers.rb` to contain `verify_mode: OpenSSL::SSL::VERIFY_NONE` in the `options` variable. Obviously this is not a solution, but is indicative of something going awry with the SSL process.

**Comment by NickHu** [comment]
It seems that my issue was my particular deployment; I was setting `SSL_CERT_DIR` and expecting ruby to check the standard certificate paths also. Regardless, I'm still happy to help get this pr merged.

**Comment by mssola** [comment]
@NickHu were these certificate problems the ones responsible for your problems with deleting images ? Otherwise, as @jmahowald is pointing out, we ask for tests for each PR (unless it's *really* trivial :P). Could you provide those ? :smiley:

**Comment by NickHu** [comment]
@mssola Yes, that's correct. I'll give tests a shot, but I'm not a rails dev - could I perhaps contact you on irc or something to avoid cluttering up this pr if I get stuck?

**Comment by mssola** [comment]
@NickHu feel free to use our [Google group](https://groups.google.com/forum/#!forum/portus-dev) :wink:

**Comment by NickHu** [comment]
@mssola I think this should be good to merge now; I've added test cases for the external hostname field and the travis failures seem to be related to gem/bundler errors which are nothing to do with this pull request.

**Comment by mssola** [comment]
Hi @NickHu, sorry for not getting back to you sooner, I was on vacation. So, the feature itself looks good to me, and the code also looks good. Now, the only thing lacking is the UX in my humble opinion.

That is, the initialization procedure for Portus feels cumbersome enough for some users, and adding a new field named like that might be more confusing. Moreover, note that the rest of the fields from the form are mandatory, so presenting this form like that might give the impression to the user that this new field is also mandatory. So, I propose the following:

- Hide this new input by default and add a link below the form saying "(Optional) Add an external hostname value"
- If the user clicks said link, the input will be shown (and the link hidden). The placeholder for the input field should be "(This is optional, leave this empty if you don't want to add an external hostname)".
- There should be an explanation stating what is an external hostname. This explanation can be in the form of a mere p tag in my opinion.

What do you think ?

**Comment by NickHu** [comment]
image
I'm still tidying it up, but how does this look?

**Comment by mssola** [comment]
That looks great. One small nitpick, when that input & text is shown, the button should say "Hide Advanced" :wink:

**Comment by NickHu** [comment]
Okay, it's done. I'm happy for this to merge.

**Comment by mssola** [comment]
Great! Thanks :clap:

**Pull request merged**
