### PR TITLE
make it possible to configure the development / staging and test DB c…

### PR DESCRIPTION
**Pull request by EugenMayer**
make it possible to configure the development / staging and test DB connection string, not only using the default. This makes it possible to debug portus instances e.g. which are production, but are broken and thus need to be started in development env, to see whats happening

### CODE REVIEW

**Comment by EugenMayer** [comment]
sorry, that one slipped through, will remove it, of course

**Comment by EugenMayer** [comment]
Looking at the travis results, seem to be general issues not related to this. HEAD is failing to compile a native exentations, 2.1.3 fails on a total unrelated point https://travis-ci.org/SUSE/Portus/jobs/164278053#L689

**Comment by monstermunchkin** [comment]
Please also be so kind and squash your commits. Just ignore travis, he's weird, and acts out sometimes.

**Comment by EugenMayer** [comment]
will do, thanks for the update

**Comment by mssola** [comment]
LGTM. Could you squash your commits into a single one and use git commit's `-s` flag to sign it off ? Thanks! :clap:

**Comment by EugenMayer** [comment]
I am sorry i am at a fair in the states and cannot work on this, i will be back next monday.

**Comment by mssola** [comment]
@EugenMayer sure, no worries. Take care :smile:

**Comment by mssola** [comment]
@EugenMayer PTAL at #1093. It supersedes this PR but it also does some other things (like allowing other RDBMS to be used). I'm not sure whether we are going to finally merge my PR, so don't close this one :wink:

**Comment by mssola** [comment]
Issue #1093 was fixed and it superseded this PR, so we can safely close this. Thanks @EugenMayer for your time 👍

**Pull request closed without merging**
