### PR TITLE
Update the website

### PR DESCRIPTION
**Pull request by cyntss**

### CODE REVIEW

**Comment by cyntss** [comment]
@flavio I included the video and added some other small fixes. Let me know if it is okay to be merged.

**Comment by flavio** [comment]
@cyntss I like the changes! There's a file conflict however, I solved that locally and I can push to the gh-pages branch for you if you want.

**Comment by mssola** [comment]
LGTM

**Comment by cyntss** [comment]
@flavio thank you for merging it :+1:

**Pull request merged**
