### PR TITLE
added env var to override and force ldap username update option

### PR DESCRIPTION
**Pull request by cpoole**

### CODE REVIEW

**Comment by monstermunchkin** [comment]
LGTM.

**Comment by mssola** [comment]
Sorry to bother you on this, but could you sign off your request ? (just adding `-s` to the git `commit` command should be enough). This is mandatory to contribute in this repo. Check the [CONTRIBUTING.md file](https://github.com/SUSE/Portus/blob/master/CONTRIBUTING.md#sign-your-work).

Besides this, the code looks good to me, really appreciated. Maybe we can also pickup this idea and use it on other places :blush:

**Comment by cpoole** [comment]
awesome, signed off. I love how strict your style guide and contributing guide is, keeps everything nice and clean!

**Comment by monstermunchkin** [comment]
Thanks :clap:

**Pull request merged**
