### PR TITLE
Front end fixes

### PR DESCRIPTION
**Pull request by cyntss**
Mayor fixes in the UI:

image

image

image

### CODE REVIEW

**Comment by mssola** [comment]
Nice! Some issues though:

1. The search item does not autofocus for me.
2. Tests are failing. This happened because you've updated the text of the sign up button and the sign up link. This is fine, it only means that the test suite has to be updated.

From my side, just fix the autofocus thing and once it gets merged, I can update the tests myself.

I'd say that you should also wait to hear the opinion of both @flavio and @eotchi :)

**Comment by flavio** [comment]
I :heart: it!

**Comment by cyntss** [comment]
thank you @flavio  :)

@mssola excellent! I will check why it doenst autofocus for you and fix it now :+1:

**Comment by mssola** [comment]
Ok, not the autofocus works for me. Thanks !

**Pull request merged**
