### PR TITLE
Annotate the models, factories and specs

### PR DESCRIPTION
**Pull request by tboerger**
In order to make the start for newbies easier I have added the annotate gem
which adds the available columns including some meta information as
documentation to the top of all models, factories and model specs.

Signed-off-by: Thomas Boerger <tboerger@suse.de>

### CODE REVIEW

**Comment by mssola** [comment]
How did you generate this ? Should be re-run some command whenever we add/remove a column ?

**Comment by tboerger** [comment]
> How did you generate this ? Should be re-run some command whenever we add/remove a column ?

Currently it's not done automatically, at least as far as I know, but as documented at https://github.com/ctran/annotate_models#configuration-in-rails we can enable auto-update on database migration.

**Comment by mssola** [comment]
Well, in there it says that by default it will do that on migrate. If that's the case, then LGTM

**Comment by tboerger** [comment]
Than it should be fine.

**Comment by mssola** [comment]
Thanks :clap:

**Pull request merged**
