### PR TITLE
js: upgraded jquery to the latest 3.x

### PR DESCRIPTION
**Pull request by vitoravelino**
Unfortunately I wasn't able to make it work while using webpack, so I moved both `jquery` and `typeahead` to the vendor directory.

### CODE REVIEW

**Comment by vitoravelino** [comment]
[Trying/Investigating jquery upgrade to 3.x](https://trello.com/c/nWTV5wxw/568-trying-investigating-jquery-upgrade-to-3x)

**Comment by mssola** [comment]
Seems that Travis does not like this change. Whenever it's green I'll review (even though right now it looks good to me 😋)

**Comment by vitoravelino** [comment]
I'm working on it.

**Comment by vitoravelino** [comment]
@mssola It's green!

**Pull request merged**
