### PR TITLE
namespace: description and team cleared when form is displayed

### PR DESCRIPTION
**Pull request by vitoravelino**
Similar to https://github.com/SUSE/Portus/pull/1213 but on namespace's form.

Signed-off-by: Vítor Avelino <contact@vitoravelino.me>

### CODE REVIEW

**Comment by mssola** [comment]
Cool. Do you need any help with the tests ?

**Comment by vitoravelino** [comment]
Fixed. I didn't remember rails generates id for hidden inputs too. Also, it's was bit confusing to understand the `if` condition since code runs every time and was being reused for different parts. 

I was hoping to maybe refactor a bit and make it more reliable on which code runs when a specific page is loaded. Not sure if is it worth it since I saw you mentioning about migrating to React/VueJS.

**Comment by mssola** [comment]
> I was hoping to maybe refactor a bit and make it more reliable on which code runs when a specific page is loaded. Not sure if is it worth it since I saw you mentioning about migrating to React/VueJS.

On making that separation for each specific case, we already tried that once and failed miserably, and that's why we are considering more modern approaches for the frontend. That being said, we are still considering it, so take it with a grain of salt 😉 

Thanks for the PR 👍

**Comment by vitoravelino** [comment]
@mssola 

That's sad to hear. I have a quick question: are you considering to move the front-end to become an independent SPA or just add a view layer on the js side to manage the components better? 

Not sure if you already have an answer, I'm just being curious.

**Comment by mssola** [comment]
> That's sad to hear. I have a quick question: are you considering to move the front-end to become an independent SPA or just add a view layer on the js side to manage the components better?

The latter. We don't want to move to a full-fledged SPA (it doesn't make much sense in our case), but we'd like to introduce more modern approaches. So adding a view layer to manage the components better would be desirable.

**Pull request merged**
