### PR TITLE
Add OpenID Connect auth.

### PR DESCRIPTION
**Pull request by dsmalko**
A new auth method using https://github.com/m0n9oose/omniauth_openid_connect.

### CODE REVIEW

**Comment by Vad1mo** [comment]
Closes #2154 
Would it make sense to get red of "OpenID 1.0". 
I frankly doubt that anyone is still using it in this world nowadays.

**Comment by shanesiebken** [comment]
As this stands, folks might run into issues with long referrer links, since we're using cookies for session store. It might be worth configuring a database session_store, setting long referrer links to nil in omniauth before_request_phase, or some other approach.

**Comment by shanesiebken** [comment]
Currently experimenting with activerecord-session_store, just pulled down your newest push to test against that.

**Comment by shanesiebken** [comment]
I have this working in a kubernetes deployment with keycloak with the activerecord-session_store. Let me know if this would be a useful addition.

**Comment by mssola** [comment]
> Closes #2154

You mean #1619, no?

> Would it make sense to get red of "OpenID 1.0". I frankly doubt that anyone is still using it in this world nowadays. What do you think @mssola?

Fine by me :+1: 

> I have this working in a kubernetes deployment with keycloak with the activerecord-session_store. Let me know if this would be a useful addition.

It would be great :+1: 

As for the failure on Travis, this is due a recent change. I will work on it whenever I have some spare time :+1:

**Comment by Vad1mo** [comment]
- Yes #1619, 
- I'll open up a new MR to remove OpenID 1.0

Is there anything else that is blocking the MR from beeing accepted?

**Comment by mssola** [comment]
@dsmalko could you squash your commits and sign them? (-s flag from git commit)

**Comment by mssola** [comment]
> @dsmalko could you squash your commits and sign them? (-s flag from git commit)

Nevermind, I always forget about the "squash and merge" feature from the merge button ...

> I'll open up a new MR to remove OpenID 1.0

Thanks!

> I have this working in a kubernetes deployment with keycloak with the activerecord-session_store. Let me know if this would be a useful addition.

Consider submitting a new PR with these changes :+1:

**Comment by shanesiebken** [comment]
I will try to do that later today!

**Pull request merged**
