### PR TITLE
if LDAP is enabled, user should be found by ldap_name

### PR DESCRIPTION
**Pull request by wangchunyang**
This is fix for issue #430

### CODE REVIEW

**Comment by mssola** [comment]
The code looks good to me. However, you have to add tests for it, that's why Travis is complaining. Feel free to add this test in a new describe block in the `spec/models/user_spec.rb` file.

**Comment by wangchunyang** [comment]
@mssola thanks. I just added a describe block and try to run "bundle exec rspec spec" on my local Windows environment to verify whether or not my changes work ok. But I got errors:

```
Fetching gem metadata from https://rubygems.org/............
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies........
Using rake 10.4.2
Using i18n 0.7.0
Installing json 1.8.3 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    C:/Ruby21-x64/bin/ruby.exe extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
generating generator-x64-mingw32.def
/bin/sh: /C/Ruby21-x64/bin/ruby: No such file or directory
Makefile:235: recipe for target 'generator-x64-mingw32.def' failed
make: *** [generator-x64-mingw32.def] Error 127

make failed, exit code 2

Gem files will remain installed in C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/json-1.8.3 for inspection.
Results logged to C:/Ruby21-x64/lib/ruby/gems/2.1.0/extensions/x64-mingw32/2.1.0/json-1.8.3/gem_make.out
An error occurred while installing json (1.8.3), and Bundler cannot continue.
Make sure that `gem install json -v '1.8.3'` succeeds before bundling.
```

**Comment by mssola** [comment]
@wangchunyang it looks like you've something on your windows setup. Could paste the contents of the log pointed by bundler?

Moreover, I can see that you're using 4-spaces for indentation in you _spec file. Change it to 2-spaces, please ;)

**Comment by wangchunyang** [comment]
@mssola I found Ruby DevKit is required to build json gem. So I installed DevKit and now "bundle install" works ok. I will continue to verify the test spec. Thanks.

**Comment by mssola** [comment]
@wangchunyang now everything seems fine (don't worry about the failing tests, it's an issue on master, we're working on it). Just squash your commits into a single one and sign off this commit (`-s` option in git commit).

**Comment by wangchunyang** [comment]
@mssola I squashed the three commits into a single one with sign-off message.

**Comment by mssola** [comment]
@wangchunyang thanks!

**Pull request merged**
