### PR TITLE
more secure docker-compose example

### PR DESCRIPTION
**Pull request by suntorytimed**
Improvement of solution for #1714
* uses SSL encryption for registry
* uses SSL encryption for frontend
* uses nginx for serving portus

Signed-off-by: Stefan Weiberg <sweiberg@suse.com>

### CODE REVIEW

**Comment by suntorytimed** [comment]
superseding #1925 and #1727

**Comment by mssola** [comment]
@suntorytimed could you rebase your commit? We just fixed a check on Travis, and it's also affecting your pull request :sweat_smile:

**Comment by suntorytimed** [comment]
@mssola done. So this might be the issue I experienced with the git error :smile:

**Comment by mssola** [comment]
@suntorytimed yeah. See #1927 :wink:

**Comment by suntorytimed** [comment]
@mssola and I thought I messed up the pull request by force pushing too much :smile:

**Comment by mssola** [comment]
Thanks :clap:

**Comment by suntorytimed** [comment]
Thanks for merging!

**Pull request merged**
