### PR TITLE
The columns of the tag-table are now sortable.

### PR DESCRIPTION
**Pull request by jloehel**
Screenshot:
screenshot - 11252015 - 06 07 39 pm

Fixes: #590 

Signed-off-by: Jürgen Löhel <jloehel@suse.com>

### CODE REVIEW

**Comment by mssola** [comment]
Good work :clap: Some notes:

- There is a gem for this `datatables` plugin. Use this instead of copying everything into the vendor directory.
- You should select just a couple of columns to sortable, not all of them.

**Comment by flavio** [comment]
Sortable columns?! :joy:

I didn't look at the code yet, but it's awesome. We will have to extend that to the other tables of course.

**Comment by mssola** [comment]
> I didn't look at the code yet, but it's awesome. We will have to extend that to the other tables of course.

Note that this was a reaction to the PR #588. But yes, we should generalize this to every column. I'll open up a new issue about this. For now, I'd prefer to keep this PR fixing the issue #588.

**Comment by mssola** [comment]
@jloehel by the way, your commit message is wrong! You're fixing the issue #590, not the PR #588 :)

**Comment by jloehel** [comment]
This pull-request will be replaced by #607.

**Pull request closed without merging**
