### PR TITLE
Add sleep time before configuring db first time

### PR DESCRIPTION
**Pull request by depay**
Portus will offen fail connecting database, if operating immediately
after mariadb container starting. So it's better adding some seconds
for waiting.

Signed-off-by: depay <depay19@163.com>

### CODE REVIEW

**Comment by mssola** [comment]
It's known that Portus will fail at connecting to the database right away, that's why we use that loop afterwards: if the connection fails, sleep for some time and try again. This loop will take 90 seconds in the worst case scenario, which most probably means that something wrong occurred on the DB side.

But maybe I'm missing something.

**Comment by depay** [comment]
i know that, just giving a sleep before first try...something change like try->sleep->try to sleep->try->sleep, for the first try always fails..

**Comment by mssola** [comment]
If this is the case, maybe you can refactor that loop so first it sleeps and then it tries to connect. Therefore, remove the docker-compose command previous to the loop, and the loop will: sleep, try the connect, and then, if it fails, print the error message and try again.

**Comment by depay** [comment]
good idea, i've updated the commit.

**Comment by mssola** [comment]
Thanks!

**Pull request merged**
