### PR TITLE
feat: track tag recreation

### PR DESCRIPTION
**Pull request by Salzig**
possible fix for #553

Signed-off-by: Ben Rexin <ben@rexin.at>

### CODE REVIEW

**Comment by Salzig** [comment]
Will fix travis later.

**Comment by mssola** [comment]
Thanks for taking care of this :)

I have one small suggestion though. If I'm not mistaken, with this we will create a new "create" activity for this tag. But this is a bit of a lie, isn't it :) Instead, in this case the activity to be created should be something like "user updated ...". What do you think?

**Comment by Salzig** [comment]
I think we could find arguments for both variants (destroy&update vs. recreate/updated). I thought it would be good to destroy the old tag, and create a new one would be less effort to implement and support in the future, as can use everything as it is right now for the sake of another database record. Alternative way would be to create a new kind of activity to distinguish between pushed and "repushed/updated" tags. 
Do you prefer the later one?

**Comment by flavio** [comment]
On Nov 14, 2015 8:30 PM, "Ben Rexin" <notifications@github.com> wrote:
>
> Alternative way would be to create a new kind of activity to distinguish
between pushed and "repushed/updated" tags.
> Do you prefer the later one?

That sounds better to me.

**Comment by Salzig** [comment]
I've to rethink this.

**Comment by mssola** [comment]
@Salzig I'd also go the later one. Thanks for taking care of this :)

**Comment by JonathonReinhart** [comment]
One possible argument for keeping this as it was originally suggested:  The "Recent activities" view currently only says "<Username> pushed <tagname>"... which is true. It doesn't say that he pushed *a new* tag, only that one was pushed at all.

**Pull request closed without merging**
