### PR TITLE
Search improvements

### PR DESCRIPTION
**Pull request by msfernandes**
Fixes: #753 

In this PR I updated the search feature to search through Teams and Namespaces too! So, I added a category menuto filter by repository, team and namespace.

screenshot-localhost 5000 2016-06-14 00-06-26
screenshot-localhost 5000 2016-06-14 00-06-54

The repository search result table is the same as before, I only added "updated_at" column. Then I show in this print a empty result :)

screenshot-localhost 5000 2016-06-14 00-07-13

And in small screens:

screencapture 1

### CODE REVIEW

**Comment by mssola** [comment]
The code looks good to me, but apparently code coverage is not at 100%. Could you look into that ?

**Comment by cyntss** [comment]
Looks excellent!

One minor change I would suggest: remove the space between the tabs and the table and then add the results numbers in the tabs =>

image

**Comment by cyntss** [comment]
I made that quickly in photoshop :p .. I didnt put the numbers in the other tabs, but they should be there as well.

**Comment by cyntss** [comment]
One last thing.. I think we could add that style in the tabs in the dashboard:

image

It would look much better!

**Comment by mssola** [comment]
Totally agree with @cynthia on the dashboard. Bear in mind though that this can be done in another PR (it is part of his GSoC to improve the dashboard :wink:).

**Comment by msfernandes** [comment]
Hi @cyntss ! Thanks for the review :)

With your suggestions:

screencapture

**Comment by mssola** [comment]
Now rubocop is the one complaining :sweat_smile:

**Comment by mssola** [comment]
Great :clap: ! Squash your commits and I'll merge it :yum:

**Pull request merged**
