### PR TITLE
ISSUE-234: namespaces name validation now also adds an error to the model now to fix #234

### LINKED ISSUE #234: Suspected validation error when creating a new team
How to reproduce:
  * Create a new team named "QA"
  * The team is listed inside of the page
  * Reload the page: the team is gone

Expected result: the team is not deleted.

### PR DESCRIPTION
**Pull request by lsamayoa**
Fixes #234

### CODE REVIEW

**Comment by flavio** [comment]
Hi, I suspected something similar was happening. In the past as soon as a team was created we used to create also a namespace named after it. This is no longer happening, so we can probably remove some validations checks from the team object.

Could you please look into that? Also it would be required to provide a test case reproducing this issue

**Comment by lsamayoa** [comment]
TODO:
- [ ] remove useless validation from teams model
- [ ] Add capybara test case for this regression

**Comment by flavio** [comment]
> Add capybara test case for this regression

I think a simple functional test should be enough.

**Comment by lsamayoa** [comment]
@flavio Done ?

**Comment by mssola** [comment]
LGTM

**Pull request merged**
