### PR TITLE
Website changes

### PR DESCRIPTION
**Pull request by flavio**
I tried to make the following changes to the website:

   * show the youtube video
   * show the asciicast about the new setup instructions

I think the asciicast is fine, it looks nice.

The youtube video has troubles: the size of the thumbnail changes according to the screen size making it blurry on big resolutions.

@cyntss: please help us!!! :smiley:

### CODE REVIEW

**Comment by cyntss** [comment]
@flavio should I have a look at this PR once im done with what im currently doing?

**Comment by flavio** [comment]
Yes, it would be nice. But also please talk with @mssola, we want to change a bit the website to have a top bar with entries like "Docs, Features,...". Most of these links are going to point to the main index page, except for the "Docs" one which is going to point to a new set of pages we want to create.

Basically we want to move all the docs from the wiki to the webiste and organize them in a better way

**Comment by cyntss** [comment]
@flavio yes sure, then on Monday I can talk to him and move forward with the website ;)

**Comment by cyntss** [comment]
im working on the youtube video atm, i will send my commit soon for you to check it

**Comment by mssola** [comment]
I'm confused, does #464 supersede this PR ?

**Comment by flavio** [comment]
@mssola yes it does

**Pull request closed without merging**
