### PR TITLE
The columns of all the tables are now sortable.

### PR DESCRIPTION
**Pull request by jloehel**
### Screenshots
screenshot - 12042015 - 03 24 36 pm
screenshot - 12042015 - 03 23 50 pm

Fixes: #600
Fixes: #590

Signed-off-by: Jürgen Löhel <jloehel@suse.com>

### CODE REVIEW

**Comment by flavio** [comment]
Wow, that looks really magical: no change inside of the controllers. Are we sure this sorting is working as expected also when pagination is involved? I fear this sorts only the visible results...

**Comment by jloehel** [comment]
The sorting happens only on the client side but I can add a remote source if you want.

**Comment by flavio** [comment]
I want to have a "traditional" behaviour: if the results are spread over different pages, sorting should take into consideration all the items.

I fear sorting on the client side takes into consideration only what is known by the client: the results of the page which is currently displayed. If that's the case we should implement sorting on the server side (where that IMHO should not happen).

Am I wrong?

**Comment by mssola** [comment]
I agree. For the `repositories#show` page this is totally fine. That being said, it would feel really weird that for sorting a table we need to hit the server honestly.

**Comment by cyphar** [comment]
Well, if we wanted to do it all client-side you'd need to do pagination on the client and send them all of the rows of the table. Which isn't that bad unless you have thousands of rows.

**Pull request closed without merging**
