### PR TITLE
Initial version of the search feature

### PR DESCRIPTION
**Pull request by flavio**
Added a simple search feature that allows to find repositories.

How it works:
  * user enters a string inside of the search box
  * a fulltext search is performed against both the repositories.name and the namespaces.name columns using the OR operator
  * results are shown inside of the new 'search' page

Mandatory s
search
creenshot

### CODE REVIEW

**Comment by flavio** [comment]
@mssola feedback is welcome as usual

**Comment by flavio** [comment]
Ok, just ignore the build errors right now. The tests are failing because the mysql db provided by travis does not support fulltext search indexes on the default engine. I'll change the travis code to use latest stable version of MariaDB instead of some old MySQL version.

**Comment by mssola** [comment]
LGTM :+1: Great Work! :)

**Comment by flavio** [comment]
Thanks

**Pull request merged**
