### PR TITLE
New: animation in the login page. 

### PR DESCRIPTION
**Pull request by cyntss**
@eotchi I need you to review this. I implemented the same animation I have in Lifeitup.

You can see it in my machine if you wanna do it quicker not checking out to my branch:
http://149.44.171.232:5000/users/sign_in

### CODE REVIEW

**Comment by flavio** [comment]
That looks fancy. Nice, but I don't know if I'm totally convinced. I'll leave the decision to @eotchi

**Comment by cyntss** [comment]
@flavio yes I leave it up to her since federica told me she liked that effect. Whatever you decide is fine by me.

**Comment by mssola** [comment]
I don't know if I'm totally convinced either. But anyways, it doesn't work for me when I'm coming from the sign up page. Is this expected, or ?

**Comment by cyntss** [comment]
@mssola no, that isnt expected, but if Federica wants it then I will open an issue and fix it :)

**Comment by mssola** [comment]
In the end we agreed that the animation should only be applied to the icon, and not to the form. Sorry for the delay.

**Comment by flavio** [comment]
That means we can close this PR. Please reopen it if I'm wrong.

**Pull request closed without merging**
