### PR TITLE
Tasks cleanup

### PR DESCRIPTION
**Pull request by flavio**
Little cleanup + new feature for portusctl

### CODE REVIEW

**Comment by mssola** [comment]
I don't know how to feel about removing the `lib/tasks/portus_user.rake` file. Recently there's been an issue in which the user had to use this rake task in order to get Portus up & running again (he was migrating from 1.0.1). I say let's keep this task around for some time at least. Maybe you could add a note to remove it in the near future?

Moreover, you should update the wiki about the set_admin -> make_admin rename once this gets merged ;)

Besides this, it looks good to me :+1:

**Comment by flavio** [comment]
> I don't know how to feel about removing the lib/tasks/portus_user.rake file. Recently there's been an issue in which the user had to use this rake task in order to get Portus up & running again (he was migrating from 1.0.1). I say let's keep this task around for some time at least. Maybe you could add a note to remove it in the near future?

This has not been deleted, it has been moved into a single file containing all the tasks defined under the `portus`'s namespace.

The task is now called: `portus:create_api_account`, which IMHO makes everything more clear.

**Comment by mssola** [comment]
@flavio I'm blind... Ok, then just ignore that comment :)

**Comment by flavio** [comment]
No worries. Thanks for the reminder about the wiki, I'll take care of that.

**Comment by flavio** [comment]
I updated the wiki section about `set_admin`.

**Pull request merged**
