### PR TITLE
Trigger automatic RPM builds for the v2.0 branch

### PR DESCRIPTION
**Pull request by flavio**
Always trigger an automatic RPM build on OBS for all the changes made to the v2.0 branch.

### CODE REVIEW

**Comment by flavio** [comment]
@ping @jordimassaguerpla and @mssola

**Comment by flavio** [comment]
Note well: we cannot send these packages to the 2.0 subproject because this is meant to be used only for official releases. Hence I created a new subproject on OBS. I also copied all the packages we have on the 2.0 project into this one.

**Comment by mssola** [comment]
LGTM

**Comment by jordimassaguerpla** [comment]
lgtm

**Pull request merged**
