### PR TITLE
Next iteration on the gh-pages site

### PR DESCRIPTION
**Pull request by mssola**
With this PR I'm finishing up the work @cyntss did for the gh-pages branch (see PR #491).

First of all, the style of the site has been greatly polished, and all the rough edges are hopefully not there anymore.

The first thing that you'll notice is that the header has two new links:

header

If you click on the "Documentation" link, you'll see the following:

documentation

The "Features" link redirects the user here:

features

As you can see, both pages share the same layout, but they have a different "presentation" page. This is done this way to be more helpful in each case. Right now I haven't done anything crazily different for each of them, but if we decide in the future to be even more specific, then it will be easier to do it.

That being said, the most important part of this layout is the section on the left. In there you can find each topic. I've structured all this in three main areas (collections in Jekyll): docs, features and setups. The contents of each of these pages have been taken from the wiki. Note that those pages that are solely development-specific have **not** been added here. This has been done on purpose, since the goal of all this is that the wiki is only used for developers. From now on, users should access this site to get all the documentation.

Moreover, to facilitate the navigation of these pages, I've added a small javascript snippet to show URL anchors for h1, h2, h3 and h4 elements. This way, when we hover the mouse over one of these elements, you'll see the following (the mouse is over the "Installing MariaDB" section):

anchor

There are some issues that I plan to fix as soon as possible though:

1. The photos for the documentation have been taken directly from our "docs" directory from the master branch.
2. These photos are from a previous iteration of Portus' UI. They need an update (mostly the ones showing the "Activities" section).

And hopefully that's all. Once this PR gets merged, I'll fix the issues described above and I'll:

1. Update the wiki.
2. Update the README and the CONTRIBUTING files.

### CODE REVIEW

**Comment by flavio** [comment]
I really like the look and feel.

A couple of suggestions:
  * when the browser window is small there's a weird horizontal scrollbar.  I think it would be nice to just hide the sidebar to give more relevance to the contents of the side (see what k8s' site does).
  * I'm not convinced by how the contents have been organized. I think most of the users want to know how to install Portus as first thing. I think we can either do a 1:1 mapping of the layout of the new wiki (note well, I'm opinionated here because I'm the author) or we can organize the docs like k8s does.

**Comment by mssola** [comment]
> I'm not convinced by how the contents have been organized. I think most of the users want to know how to install Portus as first thing. I think we can either do a 1:1 mapping of the layout of the new wiki (note well, I'm opinionated here because I'm the author) or we can organize the docs like k8s does.

So, you want the landing page for the documentation to look like the home page of the wiki. Right ?

**Comment by mssola** [comment]
By that I meant that maybe the landing page of the documentation should be more verbose in regards to how to install/configure portus and offer links. Besides that, the other pages are pretty much a 1:1 mapping compared to the ones on the wiki.

**Comment by flavio** [comment]
> So, you want the landing page for the documentation to look like the home page of the wiki. Right ?

I think the landing page is fine, I was referring to the organization of the sidebar.

**Comment by mssola** [comment]
I've now written the "Configuring your private registry" section. In this section we are now thoroughly explaining how to add a new registry to Portus, what happens when something is wrong, etc. Some fancy screenshots will help the reader to understand it better. The images have been included in this repo, since it seems that the issues I was having with images were that the `gulpfile.js` file was a bit broken (I'll have to talk with @cyntss for a proper fix though).

I've also added a much needed "Quick start guide" section. This section resides on the landing page of the documentation. The documentation landing page has also been improved, so it includes a table of contents for the documentation. This way, when users go to read our documentation, they will see:

1. What can be found in the documentation.
2. A quick start guide in order to get Portus up and running right away.
3. A section pointing readers how they can help us improve the documentation.

An image is worth a thousand words though:

documentation

**Comment by flavio** [comment]
Can you rename "SUSE Appliance" to "openSUSE Appliance"?

**Comment by flavio** [comment]
I really like it, I think we can merge it. Could you please file a bug for @cyntss about adding the possibility to hide the sidebar when the screen size is reduced?

**Comment by cyntss** [comment]
@flavio and @eotchi Please dont forget to speak to Ken and Artem to book your 2 sprints with me so we can start working on the UI this year again :+1: 
atm I'm full of work on SCC, but I assume if we plan it well, Artem can make some space in between so I can take 1 sprint in this half of the year, and the second sprint later? I leave that up to you.

**Pull request merged**
