### PR TITLE
Integrated guard into development environment

### PR DESCRIPTION
**Pull request by tboerger**
In order to make the testing while writing code easier I have integrated
guard which watches for file changes and executes the responsible specs
to get feedback from the test suite as soon as possible.

Additionally to that I have also integrated breakman checks to detect
possible security issues and I have also added rubocop to guard to keep
the code style clean.

### CODE REVIEW

**Comment by tboerger** [comment]
Maybe I should mention that you just need to execute `bin/guard` after bundling the ruby gems.

**Comment by mssola** [comment]
Cool, could you squash your commits ?

**Comment by tboerger** [comment]
> Cool, could you squash your commits ?

Which one? I have separate commits intentional.

**Comment by tboerger** [comment]
I have dropped the other commits.

**Comment by mssola** [comment]
Remove `lib/tasks/breakman.rake` and `bin/guard`. Besides this, LGTM

**Comment by flavio** [comment]
> Remove lib/tasks/breakman.rake and bin/guard. Besides this, LGTM

Why do you want to remove them, aren't they needed to run the code?

Also, do we have to integrate breakman into our CI tests?

**Comment by tboerger** [comment]
At least we should keep the breakman task as this configures brakeman. `bin/guard` is not a hard requirement as this can also be invoked by `bin/bundle exec guard`, even if i prefer the shorter one :)

**Comment by tboerger** [comment]
> Also, do we have to integrate breakman into our CI tests?

Makes sense, than it will fail if somebody introduces a possible security issue.

**Comment by mssola** [comment]
> Why do you want to remove them, aren't they needed to run the code?

The `bin/guard` file is redundant with the executable itself or `bundle exec guard`. 

> At least we should keep the breakman task as this configures brakeman.

Fair enough, seems like I read that too fast :sweat_smile: Then this file can be kept. Note though that you spelled it like breakman instead of brakeman :)

> Also, do we have to integrate breakman into our CI tests?

+1

**Comment by mssola** [comment]
Thanks :+1:

**Pull request merged**
