### PR TITLE
Fix #885: Unified alerts for namespace and teams

### LINKED ISSUE #885: unify notification messages
The notification messages differ between different pages, i.e. teams and namespaces. When a new team is created, the message is `The team 'foo' was created successfully` whereas the message for namespaces is `New namespace created`.
It would be great if these messages could be unified, e.g. `<model> '<name>' created/removed successfully`.

### PR DESCRIPTION
**Pull request by albertpaulp**
Signed-off-by: Albert Paul <albertpaulp@gmail.com>

### CODE REVIEW

**Comment by mssola** [comment]
Hey @albertpaulp. Thanks for your contribution! The code looks good to me, but the issue #885 was a bit more general I think (e.g. the same should be applied to `team_users`, `comments`, etc). Could you look into that ? Thanks :wink:

**Comment by albertpaulp** [comment]
@mssola Cool, I'll look in to it and work on it.

**Comment by monstermunchkin** [comment]
@albertpaulp are you still working on this?

**Comment by albertpaulp** [comment]
@monstermunchkin Yep, will open the new PR within 2 days.

**Comment by mssola** [comment]
Superseded by #1082.

**Pull request closed without merging**
