### PR TITLE
js: migrated webhooks index page to vue components

### PR DESCRIPTION
**Pull request by vitoravelino**
Signed-off-by: Vítor Avelino <vavelino@suse.com>

### CODE REVIEW

**Comment by vitoravelino** [comment]
This is the first of three parts of the webhooks refactoring. I'm splitting the PRs because I want to avoid a huge and almost impossible PR to be reviewed. The other two parts are the webhook show page and webhook headers.

**Comment by mssola** [comment]
I guess that you are leaving API methods for later ?

**Comment by vitoravelino** [comment]
> I guess that you are leaving API methods for later ?

Correct.

**Comment by vitoravelino** [comment]
It's green and good to be reviewed. :wink:

**Comment by mssola** [comment]
Good job :clap:

**Pull request merged**
