### PR TITLE
Logout button and search repository are now appearing in small devices

### PR DESCRIPTION
**Pull request by msfernandes**
Fixes: #772

Screenshot in a large screen:
large

Screenshot in a small screen:
small

Signed-off-by: Matheus Fernandes <matheus.souza.fernandes@gmail.com>

### CODE REVIEW

**Comment by cyphar** [comment]
Is it just me or is the alignment of the hamburger menu a little bit off?

**Comment by mssola** [comment]
As @cyphar says, the "hamburger" menu and the logout button are not centered vertically on the small screen version. Could you look into that ?

Besides that, it looks good to me, thanks :)

**Comment by msfernandes** [comment]
@mssola @cyphar 
I fixed the alignments and increased slightly the "hamburger". The printscreens in pull request description are updated

**Comment by mssola** [comment]
@msfernandes I see the same images as before :P

**Comment by msfernandes** [comment]
large
small

**Comment by mssola** [comment]
Perfect! Could you squash your commits into a single one.

**Comment by msfernandes** [comment]
@mssola done :)

**Comment by mssola** [comment]
Thanks! :clap:

**Pull request merged**
