### PR TITLE
add stylesheet information to landing page

### PR DESCRIPTION
**Pull request by jordimassaguerpla**
This works without having to modify the apache2 configuration. @flavio : good idea :) !

### CODE REVIEW

**Comment by mssola** [comment]
The link won't work. Try `/assets/aplication.css`.

**Comment by flavio** [comment]
Also what happens when the assets are changed and we rebuild the appliance? The link contains the hashed value of the assets inside of its name. This should be determined during the 1st boot

**Comment by jordimassaguerpla** [comment]
also in the rpm since an update would retrigger the precompilation of the assets

**Comment by jordimassaguerpla** [comment]
https://github.com/SUSE/Portus/blob/master/packaging/suse/Portus.spec.in#L85
I could use some "ls ..." + "sed " in the landing.html.in

**Comment by flavio** [comment]
Yes, or simply something involving "find"

**Comment by mssola** [comment]
LGTM :+1:

**Comment by flavio** [comment]
:+1:

**Pull request merged**
